# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0, verbose_name='书的id')),
                ('image_url', models.CharField(max_length=100, verbose_name='图书封面地址')),
                ('book_name', models.CharField(max_length=20, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('info', models.CharField(max_length=200, verbose_name='简介')),
                ('price', models.IntegerField(default=0, verbose_name='图书价格')),
                ('is_delete', models.IntegerField(default=0, verbose_name='图书是否下架')),
            ],
            options={
                'verbose_name': '书名',
                'verbose_name_plural': '书名',
                'db_table': 'book2',
            },
        ),
        migrations.CreateModel(
            name='Book_Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False, verbose_name='章节ID')),
                ('c_name', models.CharField(max_length=300, verbose_name='章节名称')),
                ('c_url', models.CharField(max_length=200, verbose_name='章节地址')),
                ('book_id', models.IntegerField(default=0, verbose_name='章节')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'book_chapter',
            },
        ),
        migrations.CreateModel(
            name='Book_classify2',
            fields=[
                ('cla_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类id')),
                ('name', models.CharField(max_length=20, verbose_name='书籍类别')),
            ],
            options={
                'db_table': 'book_classify2',
            },
        ),
        migrations.AddField(
            model_name='book2',
            name='classify',
            field=models.ForeignKey(db_column='cla_id', on_delete=django.db.models.deletion.DO_NOTHING, to='comments.Book_classify2', verbose_name='书籍分类'),
        ),
    ]
