# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_code', models.CharField(max_length=255, verbose_name='订单号')),
                ('address', models.CharField(max_length=255, verbose_name='配送地址')),
                ('post', models.CharField(max_length=255, verbose_name='邮编')),
                ('receiver', models.CharField(max_length=255, verbose_name='收货人')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('user_message', models.CharField(max_length=255, verbose_name='附加信息')),
                ('create_date', models.DateTimeField(max_length=0, verbose_name='创建日期')),
                ('pay_date', models.DateTimeField(blank=True, max_length=0, null=True, verbose_name='支付时间')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='交易日期')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='确认日期')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '异常'), (-1, '删除')], default=1, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('bc_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField(default=0, verbose_name='商品数量')),
                ('book', models.IntegerField(default=0, verbose_name='商品id')),
                ('status', models.IntegerField(default=1)),
                ('order', models.ForeignKey(db_column='oid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Order', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'shop_car',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('phone', models.CharField(default='15737628530', max_length=11)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'user_profile',
            },
        ),
        migrations.AddField(
            model_name='shopcar',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='car.UserProfile', verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='car.UserProfile', verbose_name='用户ID'),
        ),
    ]
